### ISSUE TITLE
Use Random Hash Function

### ISSUE THREAD

**Issue by justinpurcell1** [boxgames1/hash-tables-app#2]
Reading through your article and looking at the app, there is no mention of the importance of randomized hash functions. Using length of input can lead to many collisions (eg `Jim`, `Pam`)

**Comment by boxgames1** [comment]
Thanks for the feedback Justin. 
The hash function sends inputs with the same length to the same bucket. This is a very basic function that allows us to spread the values among buckets. I know there's better options, but this is a theoric structure.
Despite being very basic, its functionallity is enough good to show the hash tables. I don't see where is the "collision" problem.

**Comment by justinpurcell1** [comment]
By "collisions" I meant an increased likelihood that buckets will be imbalanced depending on the inputs. The less balanced the buckets are, the closer the data structure becomes to an ordinary linked list in terms of lookup and insertion time.

Just a suggestion, but in my mind this is one of the key features of hash tables.

**Comment by boxgames1** [comment]
The key of this function is that if you execute any method over a value (for example "Jim"), the target bucket will also be the same, so you know in which look for.

If you have a random function you could get bucket 2 inserting, but bucket 3 finding. In that case, it wouldn't be a hash function.

About the likelihood preocupation you have, If your table has 2 buckets, both will be loaded, if it has 100, there will be a bit softer.  You should be able to decide how many buckets you need according to the items you expect to store.

The typical production case with hash tables uses JSON's with variable lengths so buckets will be very balanced.

I hope I explained it well.

**Comment by justinpurcell1** [comment]
By random I mean that a given string has an equal likelihood in landing in any of the buckets regardless of characteristics such as length (but will land in the same bucket every time as you said).

For example, imagine I have a long list of English names (`Jim`, `Pam`, `Dwight`, etc) as in one of your examples in the article, and I have a hash table of size 100. I can guarantee that the distribution will not be uniform if length is used as the hash function, and in fact only ~10% of the buckets will have any data in them at all.

https://themeaningofthename.com/traffic-and-name-statistics/names-length-distribution/

**Comment by boxgames1** [comment]
I understand your point. In that case you expect bounded values, so have 100 buckets does not have any sense. You should be looking for instantiate the table with 8 more or less.

About the random function. Realize that every method needs a bucket's index, that is calculated with hash_function (value)

I would like to know how your random function returns the same value every time is run. Would you save any type of temporary value or some? I do not see the way. Let me know.

**Comment by justinpurcell1** [comment]
By "random" I mean that the distribution is approximately uniform for all inputs. With a good hash function you will not need to change the size of the array in order to balance it.

https://softwareengineering.stackexchange.com/questions/49550/which-hashing-algorithm-is-best-for-uniqueness-and-speed

**Comment by boxgames1** [comment]
It's a very interesting point but all hash functions have lacks (randomness, cost, distribution). There sould be a single article talking about the [Perfect Hash Function](https://en.wikipedia.org/wiki/Perfect_hash_function) but was not the target of this article.

Many thanks for the appointment.
